<?xml version="1.0" encoding="utf-8"?><Database Name="dbFoods" Class="DataClassesLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\dbFoods.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WhatShouldICook.Properties.Settings" SettingsPropertyName="dbFoodsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dinners" Member="Dinners">
    <Type Name="Dinner">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Dinner" Member="Dinner1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Soups" Member="Soups">
    <Type Name="Soup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Soup" Member="Soup1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainDishes" Member="MainDishes">
    <Type Name="MainDishe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MainDish" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>